sudo: required
dist: trusty
language: go

go:
  - 1.8

install:
  - go get -u github.com/Jumpscale/go-raml
  - go get -u -t zombiezen.com/go/capnproto2/...
  - ./tlog/install_dependencies.sh
  - sudo apt-get install capnproto

script:
  - go test -timeout 5m $(go list ./... | grep -v vendor)
  - GODEBUG=cgocheck=0 go test -timeout 5m -tags 'isal' $(go list ./... | grep -v vendor)
  - ./scripts/codegeneration.sh
