
[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/govalidator"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/etcd"

[[constraint]]
  branch = "master"
  name = "github.com/emirpasic/gods"

[[constraint]]
  branch = "master"
  name = "github.com/garyburd/redigo"

[[constraint]]
  branch = "master"
  name = "github.com/go-stack/stack"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/log15"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-isatty"

[[constraint]]
  branch = "master"
  name = "github.com/minio/blake2b-simd"

[[constraint]]
  branch = "master"
  name = "github.com/sevlyar/go-daemon"

[[constraint]]
  branch = "master"
  name = "github.com/siddontang/ledisdb"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "github.com/zero-os/0-log"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "zombiezen.com/go/capnproto2"

[[constraint]]
  branch = "master"
  name = "github.com/pierrec/lz4"

[[constraint]]
  branch = "master"
  name = "github.com/ulikunitz/xz"

[[constraint]]
  branch = "master"
  name = "github.com/secsy/goftp"

[[constraint]]
  branch = "master"
  name = "github.com/zeebo/bencode"
