
[[constraint]]
  branch = "master"
  name = "github.com/asaskevich/govalidator"

[[constraint]]
  branch = "master"
  name = "github.com/coreos/etcd"

[[constraint]]
  branch = "master"
  name = "github.com/emirpasic/gods"

[[constraint]]
  branch = "master"
  name = "github.com/garyburd/redigo"

[[constraint]]
  branch = "master"
  name = "github.com/go-stack/stack"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  branch = "master"
  name = "github.com/inconshreveable/log15"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-isatty"

[[constraint]]
  branch = "master"
  name = "github.com/minio/blake2b-simd"

[[constraint]]
  branch = "master"
  name = "github.com/sevlyar/go-daemon"

[[constraint]]
  branch = "master"
  name = "github.com/siddontang/ledisdb"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  # locked for now, as tlogserver is broken otherwise
  revision = "29a747de4ae8017c16fbd08b2f0c4b8eee102df1"
  name = "github.com/templexxx/reedsolomon"

[[constraint]]
  branch = "master"
  name = "github.com/zero-os/0-log"

[[constraint]]
  name = "gopkg.in/yaml.v2"

[[constraint]]
  branch = "master"
  name = "zombiezen.com/go/capnproto2"
